<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MVC</title>
    <script type="text/javascript" src="/js/scripts.js"></script>
    <link rel="stylesheet" href="/css/styles.css" type="text/css" />
</head>
<body>
    
    <a href="/">Home</a>
    <a href="/index.php?controller=book&amp;action=index">Books</a>
    <a href="/index.php?controller=feedback&amp;action=contact">Contact us</a>
    <hr>
    
    <div class='flash'><?=$session->getFlash() ?></div>
    
    <?=$content ?>
    <hr>
    
</body>
</html>